# Generated by Django 2.1.2 on 2019-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='encryptedUrl',
            field=models.TextField(default=None),
        ),
    ]
