# Generated by Django 2.1.2 on 2019-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0002_clip_encryptedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='encryptedUrl',
            field=models.TextField(blank=True, default=None),
        ),
    ]
