# Generated by Django 2.1.2 on 2019-01-22 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clip', '0003_auto_20190121_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 16, 11, 34, 86016, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='clip',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 22, 16, 11, 34, 86016, tzinfo=utc)),
        ),
    ]
